export default [
  {
    id: 1,
    description: 'Apresentar-me no grupo fechado para assumir meu compromisso',
    active: false,
    locked: false,
  },
  {
    id: 2,
    description: 'Assistir pelo menos três aulas antigas da Academia',
    active: false,
    locked: false,
  },
  {
    id: 3,
    description: 'Ler um dos resumos já produzidos de livros da Academia',
    active: false,
    locked: false,
  },
  {
    id: 4,
    description: 'Participar de uma Mentoria ao vivo',
    active: false,
    locked: false,
  },
  {
    id: 5,
    description: 'Entender porque o dinheiro é importante para você ',
    active: false,
    locked: false,
  },
  {
    id: 6,
    description: 'Compartilhar print do quadro com a turma com meu progresso',
    active: false,
    locked: false,
  },
  {
    id: 7,
    description: 'Completar o curso 200 em 20',
    active: false,
    locked: true,
  },
  {
    id: 8,
    description: 'Criar ou aumentar sua fonte de renda ativa',
    active: false,
    locked: true,
  },

  {
    id: 9,
    description: 'Anotar seu fluxo de caixa por 1 a 3 meses',
    active: false,
    locked: true,
  },
  {
    id: 10,
    description: 'Começar a poupar pagando primeiro a si mesmo.',
    active: false,
    locked: true,
  },
  {
    id: 11,
    description: 'Quitar todas as dividas e limpar seu nome',
    active: false,
    locked: true,
  },
  {
    id: 12,
    description: 'Compartilhar print do quadro com a turma com meu progresso',
    active: false,
    locked: true,
  },
  {
    id: 13,
    description: 'Fazer uma reserva de emergência',
    active: false,
    locked: true,
  },
  {
    id: 14,
    description: 'Construir alguma fonte de renda passiva',
    active: false,
    locked: true,
  },
  {
    id: 15,
    description: 'Completar o curso MPCA ou FIS',
    active: false,
    locked: true,
  },
  {
    id: 16,
    description: 'Definir seu perfil de investidor',
    active: false,
    locked: true,
  },
  {
    id: 17,
    description: 'Definir sua macro alocação ideal usando a fórmula 1.5+',
    active: false,
    locked: true,
  },
  {
    id: 18,
    description: 'Documentar sua politica de investimento',
    active: false,
    locked: true,
  },
  {
    id: 19,
    description: 'Escolher e abrir conta em uma corretora',
    active: false,
    locked: true,
  },
  {
    id: 20,
    description: 'Fazer o primeiro aporte',
    active: false,
    locked: true,
  },
  {
    id: 21,
    description: 'Ler o livro Mestres do Capitalismo',
    active: false,
    locked: true,
  },
  {
    id: 22,
    description: 'Compartilhar print do quadro com a turma com meu progresso',
    active: false,
    locked: true,
  },
  {
    id: 23,
    description: 'Completar o curso IP',
    active: false,
    locked: true,
  },
  {
    id: 24,
    description: 'Aportar regularmente por pelo menos três meses',
    active: false,
    locked: true,
  },
  {
    id: 25,
    description: 'Completar o cursp MPI',
    active: false,
    locked: true,
  },
  {
    id: 26,
    description: 'Rebalancear a carteira trimestralmente',
    active: false,
    locked: true,
  },
  {
    id: 27,
    description: 'Atingir uma meta de médio prazo',
    active: false,
    locked: true,
  },
  {
    id: 28,
    description: 'Compartilhar seus resultados no grupo fechado',
    active: false,
    locked: true,
  },
  {
    id: 29,
    description: 'Atingir uma meta de longo prazo',
    active: false,
    locked: true,
  },
  {
    id: 30,
    description: 'Alcançar a liberdade Financeira',
    active: false,
    locked: true,
  },
];
